## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function
## Call this function on the matrix and assign it to an object 
## first to generate a special object
makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    get <- function() x
    setin <- function(inverse) i <<- inverse
    getin <- function() i
    list(get = get, setin = setin, getin = getin)
}


## Write a short comment describing this function
## Call this function on the object generated by the first function 
## to calculate the inverse or get the cached data
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    i <- x$getin()
    if(!is.null(i)) {
        message("Getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data,...)
    x$setin(i)
    i
}
