#makeCacheMatrix creates an object that caches the inverse
#cacheSolve solves the inverse of matrix from makeCacheMatrix,
#skips calculation if inverse is already calculated
#otherwise, calculates and caches the inverse

makeCacheMatrix <- function(mat = matrix()) {
  #returns a list of four named functions:
  #(to access the functions using $ method)
  #set and get mat, set and get inv
  inv <- NULL
  
  set <- function(y) { #set/reset mat in parent
    #putting a new matrix in parent by makeCacheMatrix(x)$set(newMat),
    #cacheSolve(mat) will calculate inverse of newMat instead of mat's
    mat <<- y  #assign y to mat in the parent env
    inv <<- NULL  #clear/reset inv in parent 
    }
  
  get <- function() mat #get matrix mat from parent
  #assign value of inverse to inv in parent
  setinv <- function(inverse) inv <<- inverse  
  getinv <- function() inv
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}
  
cacheSolve <- function(mat, ...) {
  #uses an object generated by makeCacheMatrix()
  #return inverse
  inv <-mat$getinv()
  if(!is.null(inv)) {
    #get inverse from cache and skip calculation
    message("getting cached data")
    return(inv)  
  }
  
  data <-mat$get()
  inv <- solve(data, ...)  #calculate inverse from input
  #assign calculated inverse to inv in parent using setinv()
  mat$setinv(inv) 
  inv
}

#test output
# > source("test_cacheMat.R")
# >  amatrix = makeCacheMatrix(matrix(c(1,2,3,4), nrow=2, ncol=2))
# >  amatrix$get()         # Returns original matrix
# [,1] [,2]
# [1,]    1    3
# [2,]    2    4
# > cacheSolve(amatrix)   # Computes, caches, and returns    matrix inverse
# [,1] [,2]
# [1,]   -2  1.5
# [2,]    1 -0.5
# > amatrix$getinverse()  # Returns matrix inverse
# Error: attempt to apply non-function
# > amatrix$getinv()  # Returns matrix inverse
# [,1] [,2]
# [1,]   -2  1.5
# [2,]    1 -0.5
# > cacheSolve(amatrix)   # Returns cached matrix inverse using previously computed matrix inverse
# getting cached data
# [,1] [,2]
# [1,]   -2  1.5
# [2,]    1 -0.5
# > amatrix$set(matrix(c(0,5,99,66), nrow=2, ncol=2)) # Modify existing matrix
# > cacheSolve(amatrix)   # Computes, caches, and returns new matrix inverse
# [,1] [,2]
# [1,] -0.13333333  0.2
# [2,]  0.01010101  0.0
# > amatrix$get()
# [,1] [,2]
# [1,]    0   99
# [2,]    5   66
# > amatrix$getinv()  # Returns matrix inverse
# [,1] [,2]
# [1,] -0.13333333  0.2
# [2,]  0.01010101  0.0

#test time difference between first instance
#and second instance calculation
test_out = function(mat){
  tmp <- makeCacheMatrix(mat)
  time_ini <- Sys.time()
  cacheSolve(tmp)
  dur <- Sys.time() - time_ini
  print(dur)
  
  time_ini <- Sys.time()
  cacheSolve(tmp)
  dur <- Sys.time() - time_ini
  print(dur)
}

#rough sample time test
# > source("test_cacheMat.R")
# > set.seed(1234)
# > r = rnorm(1000000)
# > mat1 = matrix(r, nrow=1000, ncol=1000)
# > test_out(mat1)
# Time difference of 1.832105 secs
# getting cached data
# Time difference of 0.007000208 secs
