source('./cachematrix.R')
x <- matrix(1:20,  nrow=3, ncol=2)
y <- matrix(100:106,  nrow=3, ncol=2)
z <- matrix(c("a", "v", "b", "aa", "ab", "cc"),  nrow=3, ncol=3)
cmx <- makeCacheMatrix(x)
cmy <- makeCacheMatrix(y)
cmz <- makeCacheMatrix(z)
invx <- cacheSolve(cmx)
invy <- cacheSolve(cmy)
invz <- cacheSolve(cmz)