source('./cachematrix.R')
x <- matrix(c(2,2,3,2),  nrow=2, ncol=2)
y <- matrix(c(1, -1, 1, 2),  nrow=2, ncol=2)
cmx <- makeCacheMatrix(x)
cmy <- makeCacheMatrix(y)
invx <- cacheSolve(cmx)
invy <- cacheSolve(cmy)
solve(cacheSolve(cmy))
solve(cacheSolve(cmx))
solve(cacheSolve(cmy))
solve(cacheSolve(cmx))
